#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=RecosWTF
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --time=02:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/Homophilic_Directed_ScaleFree_Networks
source activate lr_env
srun python3 generate_recos_walker.py --model degree --beta 1.0 --hMM 0.2 --hmm 0.8